import "../styles/globals.css";
import * as React from "react";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/app/layouts/navbar";
import Footer from "@/app/layouts/footer";
import { AuthContextProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <AuthContextProvider>
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <body className={inter.className}>
            <Navbar />
            <main className="max-w-screen-xl p-2.5 m-auto">{children}</main>
            <Footer />
          </body>
        </ThemeProvider>
      </AuthContextProvider>
    </html>
  );
}
